"use client";

import React from "react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";


function FirebaseIntegration() {
  return (
    <div className="max-w-5xl mx-auto py-10 px-5">
      <h1 className="text-4xl font-bold text-center mb-8">
        🔥 Firebase Integration in Flutter
      </h1>

      <div className="space-y-8">
        {/* 1. Introduction */}
        <Card className="p-6 shadow-lg border-t-4 border-blue-500">
          <h2 className="text-2xl font-semibold mb-4">1. Introduction</h2>
          <p className="text-gray-700 leading-relaxed">
            Firebase provides backend services like authentication, database, storage,
            and analytics for your Flutter apps. In this module, we'll integrate
            Firebase for **Authentication** and **Firestore Database**.
          </p>
        </Card>

        {/* 2. Setting up Firebase */}
        <Card className="p-6 shadow-lg border-t-4 border-purple-500">
          <h2 className="text-2xl font-semibold mb-4">2. Setting up Firebase</h2>
          <ol className="list-decimal pl-6 space-y-2 text-gray-700">
            <li>Go to <a href="https://console.firebase.google.com" className="text-blue-600 underline">Firebase Console</a> and create a new project.</li>
            <li>Add an Android/iOS app in the project settings.</li>
            <li>Download <code>google-services.json</code> (Android) or <code>GoogleService-Info.plist</code> (iOS) and place it in your Flutter project.</li>
            <li>Add dependencies in <code>pubspec.yaml</code>:</li>
          </ol>

          <pre className="bg-gray-100 p-4 rounded-md text-sm overflow-x-auto mt-3">
{`dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.22.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.1.0`}
          </pre>
        </Card>

        {/* 3. Initializing Firebase */}
        <Card className="p-6 shadow-lg border-t-4 border-green-500">
          <h2 className="text-2xl font-semibold mb-4">3. Initializing Firebase</h2>
          <pre className="bg-gray-100 p-4 rounded-md text-sm overflow-x-auto">
{`import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by flutterfire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(MyApp());
}`}
          </pre>
        </Card>

        {/* 4. Email & Password Authentication */}
        <Card className="p-6 shadow-lg border-t-4 border-yellow-500">
          <h2 className="text-2xl font-semibold mb-4">4. Email & Password Authentication</h2>
          <p className="text-gray-700 mb-3">
            Use <code>firebase_auth</code> to sign up, sign in, and sign out users.
          </p>

          <pre className="bg-gray-100 p-4 rounded-md text-sm overflow-x-auto">
{`import 'package:firebase_auth/firebase_auth.dart';

final FirebaseAuth _auth = FirebaseAuth.instance;

// Sign Up
Future<User?> signUp(String email, String password) async {
  try {
    UserCredential result = await _auth.createUserWithEmailAndPassword(
      email: email,
      password: password,
    );
    return result.user;
  } catch (e) {
    print('Sign Up Error: \$e');
    return null;
  }
}

// Sign In
Future<User?> signIn(String email, String password) async {
  try {
    UserCredential result = await _auth.signInWithEmailAndPassword(
      email: email,
      password: password,
    );
    return result.user;
  } catch (e) {
    print('Sign In Error: \$e');
    return null;
  }
}

// Sign Out
Future<void> signOut() async {
  await _auth.signOut();
}`}
          </pre>
        </Card>

        {/* 5. Google Authentication */}
        <Card className="p-6 shadow-lg border-t-4 border-pink-500">
          <h2 className="text-2xl font-semibold mb-4">5. Google Authentication</h2>
          <p className="text-gray-700 mb-3">
            Firebase supports Google Sign-In using <code>google_sign_in</code> package:
          </p>

          <pre className="bg-gray-100 p-4 rounded-md text-sm overflow-x-auto">
{`import 'package:google_sign_in/google_sign_in.dart';
import 'package:firebase_auth/firebase_auth.dart';

final GoogleSignIn _googleSignIn = GoogleSignIn();

Future<User?> signInWithGoogle() async {
  try {
    final GoogleSignInAccount? googleUser = await _googleSignIn.signIn();
    final GoogleSignInAuthentication googleAuth = await googleUser!.authentication;
    
    final credential = GoogleAuthProvider.credential(
      accessToken: googleAuth.accessToken,
      idToken: googleAuth.idToken,
    );

    UserCredential userCredential = await FirebaseAuth.instance.signInWithCredential(credential);
    return userCredential.user;
  } catch (e) {
    print('Google Sign-In Error: \$e');
    return null;
  }
}`}
          </pre>
        </Card>

        {/* 6. Firestore Database */}
        <Card className="p-6 shadow-lg border-t-4 border-indigo-500">
          <h2 className="text-2xl font-semibold mb-4">6. Firestore Database</h2>
          <p className="text-gray-700 mb-3">
            Firestore allows storing structured data. Example: storing a user profile.
          </p>

          <pre className="bg-gray-100 p-4 rounded-md text-sm overflow-x-auto">
{`import 'package:cloud_firestore/cloud_firestore.dart';

final FirebaseFirestore _firestore = FirebaseFirestore.instance;

// Add User
Future<void> addUser(String uid, String name, String email) async {
  await _firestore.collection('users').doc(uid).set({
    'name': name,
    'email': email,
    'createdAt': FieldValue.serverTimestamp(),
  });
}

// Fetch Users
Stream<QuerySnapshot> getUsers() {
  return _firestore.collection('users').snapshots();
}`}
          </pre>
        </Card>

        {/* 7. Hands-on Mini Project */}
        <Card className="p-6 shadow-lg border-t-4 border-teal-500">
          <h2 className="text-2xl font-semibold mb-4">7. Mini Project: Firebase Auth + Firestore App</h2>
          <p className="text-gray-700 mb-3">
            Create a simple app where users can:
          </p>
          <ul className="list-disc pl-6 text-gray-700 space-y-2">
            <li>Sign up / Sign in using email & password or Google.</li>
            <li>Save user profile in Firestore.</li>
            <li>Display list of users in real-time.</li>
          </ul>
        </Card>

        
      </div>
    </div>
  );
}



export default FirebaseIntegration;